// Generated const names intentionally contain lowercase label/instance segments
// for readability in expansion output.
#![allow(non_upper_case_globals)]

//! Test target crate for macro expansion debugging.
//!
//! Each module exercises a specific scenario so that an expansion debugger
//! can verify it distinguishes every expansion correctly.
//!
//! To inspect expansions:
//!   cargo expand -p debug-target
//!   cargo expand -p debug-target -- module_name

use debug_macros::{emit_trace, trace_attr, TraceDerive};

// ---------------------------------------------------------------------------
// 1. Function-like proc macro applied multiple times with different labels.
//    Verify: alpha and beta expansions don't mix; generated macro_rules!
//    invocations are visible.
// ---------------------------------------------------------------------------
pub mod case_fnlike {
    use super::*;

    emit_trace!(alpha);
    emit_trace!(beta);
}

// ---------------------------------------------------------------------------
// 2. Attribute macro applied to different targets with the same label/instance.
//    Verify: same macro + same label/instance, different targets → distinct.
// ---------------------------------------------------------------------------
pub mod case_attr_different_targets {
    use super::*;

    #[trace_attr(alpha, first)]
    pub struct A1;

    #[trace_attr(alpha, first)]
    pub struct A2;
}

// ---------------------------------------------------------------------------
// 3. Attribute macro applied multiple times to the same target.
//    Verify: same target, different instances → distinct.
// ---------------------------------------------------------------------------
pub mod case_attr_same_target {
    use super::*;

    #[trace_attr(alpha, first)]
    #[trace_attr(alpha, second)]
    pub struct A;
}

// ---------------------------------------------------------------------------
// 4. Derive macro applied to different targets.
//    Verify: derive expansions don't mix.
// ---------------------------------------------------------------------------
pub mod case_derive {
    use super::*;

    #[derive(TraceDerive)]
    #[trace_derive(alpha, first)]
    pub struct D1;

    #[derive(TraceDerive)]
    #[trace_derive(alpha, second)]
    pub struct D2;
}

// ---------------------------------------------------------------------------
// 5. Mixed: all three macro kinds used close together.
//    Verify: different macro kinds are distinguishable even when adjacent.
// ---------------------------------------------------------------------------
pub mod case_mixed {
    use super::*;

    emit_trace!(gamma);

    #[trace_attr(beta, one)]
    pub struct M1;

    #[derive(TraceDerive)]
    #[trace_derive(beta, two)]
    pub struct M2;

    emit_trace!(delta);
}

// ---------------------------------------------------------------------------
// 6. Declarative macro (macro_rules!) for comparison.
//    This is a simple macro_rules! defined here (not generated by a proc macro)
//    to serve as a baseline when observing expansion differences.
// ---------------------------------------------------------------------------
pub mod case_decl_macro {
    macro_rules! decl_trace {
        ($label:ident) => {
            pub const __TRACE_DECL: &str = concat!("decl:", stringify!($label));
        };
    }

    decl_trace!(alpha);
    // Note: a second invocation in the same module would conflict on the const name,
    // so we use a submodule to show two distinct expansions.
    pub mod sub {
        macro_rules! decl_trace {
            ($label:ident) => {
                pub const __TRACE_DECL: &str = concat!("decl:", stringify!($label));
            };
        }
        decl_trace!(beta);
    }
}
